//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5472
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.5472.
// 
#pragma warning disable 1591

namespace CedForecastRN.WS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SincronizacionSoap", Namespace="http://cedeira.com.ar/")]
    public partial class Sincronizacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FechaUltimaSincronizacionArticulosOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaUltimaSincronizacionCuentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaUltimaSincronizacionClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaUltimaSincronizacionZonasOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarArticuloOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback IniciarEnvioVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TerminarEnvioVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarZonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarFamiliasArticuloOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarFamiliaArticuloOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarFamiliasArticuloXArticuloOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarFamiliaArticuloXArticuloOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecibirRollingForecastOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecibirProyeccionAnualOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Sincronizacion() {
            this.Url = global::CedForecastRN.Properties.Settings.Default.CedForecastRN_WS_Sincronizacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FechaUltimaSincronizacionArticulosCompletedEventHandler FechaUltimaSincronizacionArticulosCompleted;
        
        /// <remarks/>
        public event FechaUltimaSincronizacionCuentasCompletedEventHandler FechaUltimaSincronizacionCuentasCompleted;
        
        /// <remarks/>
        public event FechaUltimaSincronizacionClientesCompletedEventHandler FechaUltimaSincronizacionClientesCompleted;
        
        /// <remarks/>
        public event FechaUltimaSincronizacionZonasCompletedEventHandler FechaUltimaSincronizacionZonasCompleted;
        
        /// <remarks/>
        public event EnviarArticuloCompletedEventHandler EnviarArticuloCompleted;
        
        /// <remarks/>
        public event EnviarCuentaCompletedEventHandler EnviarCuentaCompleted;
        
        /// <remarks/>
        public event EnviarClienteCompletedEventHandler EnviarClienteCompleted;
        
        /// <remarks/>
        public event IniciarEnvioVentaCompletedEventHandler IniciarEnvioVentaCompleted;
        
        /// <remarks/>
        public event EnviarVentaCompletedEventHandler EnviarVentaCompleted;
        
        /// <remarks/>
        public event TerminarEnvioVentaCompletedEventHandler TerminarEnvioVentaCompleted;
        
        /// <remarks/>
        public event EnviarZonaCompletedEventHandler EnviarZonaCompleted;
        
        /// <remarks/>
        public event EliminarFamiliasArticuloCompletedEventHandler EliminarFamiliasArticuloCompleted;
        
        /// <remarks/>
        public event EnviarFamiliaArticuloCompletedEventHandler EnviarFamiliaArticuloCompleted;
        
        /// <remarks/>
        public event EliminarFamiliasArticuloXArticuloCompletedEventHandler EliminarFamiliasArticuloXArticuloCompleted;
        
        /// <remarks/>
        public event EnviarFamiliaArticuloXArticuloCompletedEventHandler EnviarFamiliaArticuloXArticuloCompleted;
        
        /// <remarks/>
        public event RecibirRollingForecastCompletedEventHandler RecibirRollingForecastCompleted;
        
        /// <remarks/>
        public event RecibirProyeccionAnualCompletedEventHandler RecibirProyeccionAnualCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/FechaUltimaSincronizacionArticulos", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime FechaUltimaSincronizacionArticulos() {
            object[] results = this.Invoke("FechaUltimaSincronizacionArticulos", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionArticulosAsync() {
            this.FechaUltimaSincronizacionArticulosAsync(null);
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionArticulosAsync(object userState) {
            if ((this.FechaUltimaSincronizacionArticulosOperationCompleted == null)) {
                this.FechaUltimaSincronizacionArticulosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaUltimaSincronizacionArticulosOperationCompleted);
            }
            this.InvokeAsync("FechaUltimaSincronizacionArticulos", new object[0], this.FechaUltimaSincronizacionArticulosOperationCompleted, userState);
        }
        
        private void OnFechaUltimaSincronizacionArticulosOperationCompleted(object arg) {
            if ((this.FechaUltimaSincronizacionArticulosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaUltimaSincronizacionArticulosCompleted(this, new FechaUltimaSincronizacionArticulosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/FechaUltimaSincronizacionCuentas", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime FechaUltimaSincronizacionCuentas() {
            object[] results = this.Invoke("FechaUltimaSincronizacionCuentas", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionCuentasAsync() {
            this.FechaUltimaSincronizacionCuentasAsync(null);
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionCuentasAsync(object userState) {
            if ((this.FechaUltimaSincronizacionCuentasOperationCompleted == null)) {
                this.FechaUltimaSincronizacionCuentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaUltimaSincronizacionCuentasOperationCompleted);
            }
            this.InvokeAsync("FechaUltimaSincronizacionCuentas", new object[0], this.FechaUltimaSincronizacionCuentasOperationCompleted, userState);
        }
        
        private void OnFechaUltimaSincronizacionCuentasOperationCompleted(object arg) {
            if ((this.FechaUltimaSincronizacionCuentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaUltimaSincronizacionCuentasCompleted(this, new FechaUltimaSincronizacionCuentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/FechaUltimaSincronizacionClientes", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime FechaUltimaSincronizacionClientes() {
            object[] results = this.Invoke("FechaUltimaSincronizacionClientes", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionClientesAsync() {
            this.FechaUltimaSincronizacionClientesAsync(null);
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionClientesAsync(object userState) {
            if ((this.FechaUltimaSincronizacionClientesOperationCompleted == null)) {
                this.FechaUltimaSincronizacionClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaUltimaSincronizacionClientesOperationCompleted);
            }
            this.InvokeAsync("FechaUltimaSincronizacionClientes", new object[0], this.FechaUltimaSincronizacionClientesOperationCompleted, userState);
        }
        
        private void OnFechaUltimaSincronizacionClientesOperationCompleted(object arg) {
            if ((this.FechaUltimaSincronizacionClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaUltimaSincronizacionClientesCompleted(this, new FechaUltimaSincronizacionClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/FechaUltimaSincronizacionZonas", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime FechaUltimaSincronizacionZonas() {
            object[] results = this.Invoke("FechaUltimaSincronizacionZonas", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionZonasAsync() {
            this.FechaUltimaSincronizacionZonasAsync(null);
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionZonasAsync(object userState) {
            if ((this.FechaUltimaSincronizacionZonasOperationCompleted == null)) {
                this.FechaUltimaSincronizacionZonasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaUltimaSincronizacionZonasOperationCompleted);
            }
            this.InvokeAsync("FechaUltimaSincronizacionZonas", new object[0], this.FechaUltimaSincronizacionZonasOperationCompleted, userState);
        }
        
        private void OnFechaUltimaSincronizacionZonasOperationCompleted(object arg) {
            if ((this.FechaUltimaSincronizacionZonasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaUltimaSincronizacionZonasCompleted(this, new FechaUltimaSincronizacionZonasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarArticulo", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarArticulo(Articulo Elemento) {
            this.Invoke("EnviarArticulo", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarArticuloAsync(Articulo Elemento) {
            this.EnviarArticuloAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarArticuloAsync(Articulo Elemento, object userState) {
            if ((this.EnviarArticuloOperationCompleted == null)) {
                this.EnviarArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarArticuloOperationCompleted);
            }
            this.InvokeAsync("EnviarArticulo", new object[] {
                        Elemento}, this.EnviarArticuloOperationCompleted, userState);
        }
        
        private void OnEnviarArticuloOperationCompleted(object arg) {
            if ((this.EnviarArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarArticuloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarCuenta", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarCuenta(Cuenta Elemento) {
            this.Invoke("EnviarCuenta", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarCuentaAsync(Cuenta Elemento) {
            this.EnviarCuentaAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarCuentaAsync(Cuenta Elemento, object userState) {
            if ((this.EnviarCuentaOperationCompleted == null)) {
                this.EnviarCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarCuentaOperationCompleted);
            }
            this.InvokeAsync("EnviarCuenta", new object[] {
                        Elemento}, this.EnviarCuentaOperationCompleted, userState);
        }
        
        private void OnEnviarCuentaOperationCompleted(object arg) {
            if ((this.EnviarCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarCuentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarCliente", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarCliente(Cliente Elemento) {
            this.Invoke("EnviarCliente", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarClienteAsync(Cliente Elemento) {
            this.EnviarClienteAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarClienteAsync(Cliente Elemento, object userState) {
            if ((this.EnviarClienteOperationCompleted == null)) {
                this.EnviarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarClienteOperationCompleted);
            }
            this.InvokeAsync("EnviarCliente", new object[] {
                        Elemento}, this.EnviarClienteOperationCompleted, userState);
        }
        
        private void OnEnviarClienteOperationCompleted(object arg) {
            if ((this.EnviarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/IniciarEnvioVenta", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IniciarEnvioVenta() {
            this.Invoke("IniciarEnvioVenta", new object[0]);
        }
        
        /// <remarks/>
        public void IniciarEnvioVentaAsync() {
            this.IniciarEnvioVentaAsync(null);
        }
        
        /// <remarks/>
        public void IniciarEnvioVentaAsync(object userState) {
            if ((this.IniciarEnvioVentaOperationCompleted == null)) {
                this.IniciarEnvioVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarEnvioVentaOperationCompleted);
            }
            this.InvokeAsync("IniciarEnvioVenta", new object[0], this.IniciarEnvioVentaOperationCompleted, userState);
        }
        
        private void OnIniciarEnvioVentaOperationCompleted(object arg) {
            if ((this.IniciarEnvioVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarEnvioVentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarVenta", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarVenta(Venta Elemento) {
            this.Invoke("EnviarVenta", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarVentaAsync(Venta Elemento) {
            this.EnviarVentaAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarVentaAsync(Venta Elemento, object userState) {
            if ((this.EnviarVentaOperationCompleted == null)) {
                this.EnviarVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarVentaOperationCompleted);
            }
            this.InvokeAsync("EnviarVenta", new object[] {
                        Elemento}, this.EnviarVentaOperationCompleted, userState);
        }
        
        private void OnEnviarVentaOperationCompleted(object arg) {
            if ((this.EnviarVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarVentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/TerminarEnvioVenta", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TerminarEnvioVenta() {
            this.Invoke("TerminarEnvioVenta", new object[0]);
        }
        
        /// <remarks/>
        public void TerminarEnvioVentaAsync() {
            this.TerminarEnvioVentaAsync(null);
        }
        
        /// <remarks/>
        public void TerminarEnvioVentaAsync(object userState) {
            if ((this.TerminarEnvioVentaOperationCompleted == null)) {
                this.TerminarEnvioVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTerminarEnvioVentaOperationCompleted);
            }
            this.InvokeAsync("TerminarEnvioVenta", new object[0], this.TerminarEnvioVentaOperationCompleted, userState);
        }
        
        private void OnTerminarEnvioVentaOperationCompleted(object arg) {
            if ((this.TerminarEnvioVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TerminarEnvioVentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarZona", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarZona(Zona Elemento) {
            this.Invoke("EnviarZona", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarZonaAsync(Zona Elemento) {
            this.EnviarZonaAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarZonaAsync(Zona Elemento, object userState) {
            if ((this.EnviarZonaOperationCompleted == null)) {
                this.EnviarZonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarZonaOperationCompleted);
            }
            this.InvokeAsync("EnviarZona", new object[] {
                        Elemento}, this.EnviarZonaOperationCompleted, userState);
        }
        
        private void OnEnviarZonaOperationCompleted(object arg) {
            if ((this.EnviarZonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarZonaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EliminarFamiliasArticulo", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarFamiliasArticulo() {
            this.Invoke("EliminarFamiliasArticulo", new object[0]);
        }
        
        /// <remarks/>
        public void EliminarFamiliasArticuloAsync() {
            this.EliminarFamiliasArticuloAsync(null);
        }
        
        /// <remarks/>
        public void EliminarFamiliasArticuloAsync(object userState) {
            if ((this.EliminarFamiliasArticuloOperationCompleted == null)) {
                this.EliminarFamiliasArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarFamiliasArticuloOperationCompleted);
            }
            this.InvokeAsync("EliminarFamiliasArticulo", new object[0], this.EliminarFamiliasArticuloOperationCompleted, userState);
        }
        
        private void OnEliminarFamiliasArticuloOperationCompleted(object arg) {
            if ((this.EliminarFamiliasArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarFamiliasArticuloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarFamiliaArticulo", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarFamiliaArticulo(FamiliaArticulo Elemento) {
            this.Invoke("EnviarFamiliaArticulo", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarFamiliaArticuloAsync(FamiliaArticulo Elemento) {
            this.EnviarFamiliaArticuloAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarFamiliaArticuloAsync(FamiliaArticulo Elemento, object userState) {
            if ((this.EnviarFamiliaArticuloOperationCompleted == null)) {
                this.EnviarFamiliaArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarFamiliaArticuloOperationCompleted);
            }
            this.InvokeAsync("EnviarFamiliaArticulo", new object[] {
                        Elemento}, this.EnviarFamiliaArticuloOperationCompleted, userState);
        }
        
        private void OnEnviarFamiliaArticuloOperationCompleted(object arg) {
            if ((this.EnviarFamiliaArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarFamiliaArticuloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EliminarFamiliasArticuloXArticulo", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarFamiliasArticuloXArticulo() {
            this.Invoke("EliminarFamiliasArticuloXArticulo", new object[0]);
        }
        
        /// <remarks/>
        public void EliminarFamiliasArticuloXArticuloAsync() {
            this.EliminarFamiliasArticuloXArticuloAsync(null);
        }
        
        /// <remarks/>
        public void EliminarFamiliasArticuloXArticuloAsync(object userState) {
            if ((this.EliminarFamiliasArticuloXArticuloOperationCompleted == null)) {
                this.EliminarFamiliasArticuloXArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarFamiliasArticuloXArticuloOperationCompleted);
            }
            this.InvokeAsync("EliminarFamiliasArticuloXArticulo", new object[0], this.EliminarFamiliasArticuloXArticuloOperationCompleted, userState);
        }
        
        private void OnEliminarFamiliasArticuloXArticuloOperationCompleted(object arg) {
            if ((this.EliminarFamiliasArticuloXArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarFamiliasArticuloXArticuloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarFamiliaArticuloXArticulo", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarFamiliaArticuloXArticulo(FamiliaArticuloXArticulo Elemento) {
            this.Invoke("EnviarFamiliaArticuloXArticulo", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarFamiliaArticuloXArticuloAsync(FamiliaArticuloXArticulo Elemento) {
            this.EnviarFamiliaArticuloXArticuloAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarFamiliaArticuloXArticuloAsync(FamiliaArticuloXArticulo Elemento, object userState) {
            if ((this.EnviarFamiliaArticuloXArticuloOperationCompleted == null)) {
                this.EnviarFamiliaArticuloXArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarFamiliaArticuloXArticuloOperationCompleted);
            }
            this.InvokeAsync("EnviarFamiliaArticuloXArticulo", new object[] {
                        Elemento}, this.EnviarFamiliaArticuloXArticuloOperationCompleted, userState);
        }
        
        private void OnEnviarFamiliaArticuloXArticuloOperationCompleted(object arg) {
            if ((this.EnviarFamiliaArticuloXArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarFamiliaArticuloXArticuloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/RecibirRollingForecast", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Forecast[] RecibirRollingForecast(string Periodo) {
            object[] results = this.Invoke("RecibirRollingForecast", new object[] {
                        Periodo});
            return ((Forecast[])(results[0]));
        }
        
        /// <remarks/>
        public void RecibirRollingForecastAsync(string Periodo) {
            this.RecibirRollingForecastAsync(Periodo, null);
        }
        
        /// <remarks/>
        public void RecibirRollingForecastAsync(string Periodo, object userState) {
            if ((this.RecibirRollingForecastOperationCompleted == null)) {
                this.RecibirRollingForecastOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecibirRollingForecastOperationCompleted);
            }
            this.InvokeAsync("RecibirRollingForecast", new object[] {
                        Periodo}, this.RecibirRollingForecastOperationCompleted, userState);
        }
        
        private void OnRecibirRollingForecastOperationCompleted(object arg) {
            if ((this.RecibirRollingForecastCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecibirRollingForecastCompleted(this, new RecibirRollingForecastCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/RecibirProyeccionAnual", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Forecast[] RecibirProyeccionAnual(string Periodo) {
            object[] results = this.Invoke("RecibirProyeccionAnual", new object[] {
                        Periodo});
            return ((Forecast[])(results[0]));
        }
        
        /// <remarks/>
        public void RecibirProyeccionAnualAsync(string Periodo) {
            this.RecibirProyeccionAnualAsync(Periodo, null);
        }
        
        /// <remarks/>
        public void RecibirProyeccionAnualAsync(string Periodo, object userState) {
            if ((this.RecibirProyeccionAnualOperationCompleted == null)) {
                this.RecibirProyeccionAnualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecibirProyeccionAnualOperationCompleted);
            }
            this.InvokeAsync("RecibirProyeccionAnual", new object[] {
                        Periodo}, this.RecibirProyeccionAnualOperationCompleted, userState);
        }
        
        private void OnRecibirProyeccionAnualOperationCompleted(object arg) {
            if ((this.RecibirProyeccionAnualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecibirProyeccionAnualCompleted(this, new RecibirProyeccionAnualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Articulo {
        
        private string idField;
        
        private string descrField;
        
        private decimal pesoBrutoField;
        
        private string unidadMedidaField;
        
        private bool habilitadoField;
        
        private System.DateTime fechaUltModifField;
        
        private GrupoArticulo grupoArticuloField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
        
        /// <comentarios/>
        public decimal PesoBruto {
            get {
                return this.pesoBrutoField;
            }
            set {
                this.pesoBrutoField = value;
            }
        }
        
        /// <comentarios/>
        public string UnidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
            }
        }
        
        /// <comentarios/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaUltModif {
            get {
                return this.fechaUltModifField;
            }
            set {
                this.fechaUltModifField = value;
            }
        }
        
        /// <comentarios/>
        public GrupoArticulo GrupoArticulo {
            get {
                return this.grupoArticuloField;
            }
            set {
                this.grupoArticuloField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class GrupoArticulo {
        
        private string idGrupoArticuloField;
        
        private string descrGrupoArticuloField;
        
        private Division divisionField;
        
        /// <comentarios/>
        public string IdGrupoArticulo {
            get {
                return this.idGrupoArticuloField;
            }
            set {
                this.idGrupoArticuloField = value;
            }
        }
        
        /// <comentarios/>
        public string DescrGrupoArticulo {
            get {
                return this.descrGrupoArticuloField;
            }
            set {
                this.descrGrupoArticuloField = value;
            }
        }
        
        /// <comentarios/>
        public Division Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Division {
        
        private string idField;
        
        private string descrField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Forecast {
        
        private string idTipoPlanillaField;
        
        private string idCuentaField;
        
        private Cliente clienteField;
        
        private Articulo articuloField;
        
        private string idPeriodoField;
        
        private decimal cantidadField;
        
        /// <comentarios/>
        public string IdTipoPlanilla {
            get {
                return this.idTipoPlanillaField;
            }
            set {
                this.idTipoPlanillaField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCuenta {
            get {
                return this.idCuentaField;
            }
            set {
                this.idCuentaField = value;
            }
        }
        
        /// <comentarios/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <comentarios/>
        public Articulo Articulo {
            get {
                return this.articuloField;
            }
            set {
                this.articuloField = value;
            }
        }
        
        /// <comentarios/>
        public string IdPeriodo {
            get {
                return this.idPeriodoField;
            }
            set {
                this.idPeriodoField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Cliente {
        
        private string idField;
        
        private string descrField;
        
        private Zona zonaField;
        
        private bool habilitadoField;
        
        private System.DateTime fechaUltModifField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
        
        /// <comentarios/>
        public Zona Zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
            }
        }
        
        /// <comentarios/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaUltModif {
            get {
                return this.fechaUltModifField;
            }
            set {
                this.fechaUltModifField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Zona {
        
        private string idField;
        
        private string descrField;
        
        private bool habilitadaField;
        
        private System.DateTime fechaUltModifField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
        
        /// <comentarios/>
        public bool Habilitada {
            get {
                return this.habilitadaField;
            }
            set {
                this.habilitadaField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaUltModif {
            get {
                return this.fechaUltModifField;
            }
            set {
                this.fechaUltModifField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class FamiliaArticuloXArticulo {
        
        private string idField;
        
        private FamiliaArticulo familiaField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public FamiliaArticulo Familia {
            get {
                return this.familiaField;
            }
            set {
                this.familiaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class FamiliaArticulo {
        
        private string idField;
        
        private string descrField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Venta {
        
        private string idPeriodoField;
        
        private string idArticuloField;
        
        private string idClienteField;
        
        private decimal cantidadField;
        
        /// <comentarios/>
        public string IdPeriodo {
            get {
                return this.idPeriodoField;
            }
            set {
                this.idPeriodoField = value;
            }
        }
        
        /// <comentarios/>
        public string IdArticulo {
            get {
                return this.idArticuloField;
            }
            set {
                this.idArticuloField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class PaginaDefault {
        
        private string idField;
        
        private string descrField;
        
        private string uRLField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
        
        /// <comentarios/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class EstadoCuenta {
        
        private string idField;
        
        private string descrField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class TipoCuenta {
        
        private string idField;
        
        private string descrField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Cuenta {
        
        private string idField;
        
        private string nombreField;
        
        private string telefonoField;
        
        private string emailField;
        
        private Division divisionField;
        
        private string passwordField;
        
        private string confirmacionPasswordField;
        
        private string preguntaField;
        
        private string respuestaField;
        
        private TipoCuenta tipoCuentaField;
        
        private EstadoCuenta estadoCuentaField;
        
        private System.DateTime fechaAltaField;
        
        private int cantidadEnviosMailField;
        
        private System.DateTime fechaUltimoReenvioMailField;
        
        private string emailSMSField;
        
        private bool recibeAvisoAltaCuentaField;
        
        private PaginaDefault paginaDefaultField;
        
        private System.DateTime fechaUltModifField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <comentarios/>
        public Division Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <comentarios/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <comentarios/>
        public string ConfirmacionPassword {
            get {
                return this.confirmacionPasswordField;
            }
            set {
                this.confirmacionPasswordField = value;
            }
        }
        
        /// <comentarios/>
        public string Pregunta {
            get {
                return this.preguntaField;
            }
            set {
                this.preguntaField = value;
            }
        }
        
        /// <comentarios/>
        public string Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <comentarios/>
        public TipoCuenta TipoCuenta {
            get {
                return this.tipoCuentaField;
            }
            set {
                this.tipoCuentaField = value;
            }
        }
        
        /// <comentarios/>
        public EstadoCuenta EstadoCuenta {
            get {
                return this.estadoCuentaField;
            }
            set {
                this.estadoCuentaField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaAlta {
            get {
                return this.fechaAltaField;
            }
            set {
                this.fechaAltaField = value;
            }
        }
        
        /// <comentarios/>
        public int CantidadEnviosMail {
            get {
                return this.cantidadEnviosMailField;
            }
            set {
                this.cantidadEnviosMailField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaUltimoReenvioMail {
            get {
                return this.fechaUltimoReenvioMailField;
            }
            set {
                this.fechaUltimoReenvioMailField = value;
            }
        }
        
        /// <comentarios/>
        public string EmailSMS {
            get {
                return this.emailSMSField;
            }
            set {
                this.emailSMSField = value;
            }
        }
        
        /// <comentarios/>
        public bool RecibeAvisoAltaCuenta {
            get {
                return this.recibeAvisoAltaCuentaField;
            }
            set {
                this.recibeAvisoAltaCuentaField = value;
            }
        }
        
        /// <comentarios/>
        public PaginaDefault PaginaDefault {
            get {
                return this.paginaDefaultField;
            }
            set {
                this.paginaDefaultField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaUltModif {
            get {
                return this.fechaUltModifField;
            }
            set {
                this.fechaUltModifField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void FechaUltimaSincronizacionArticulosCompletedEventHandler(object sender, FechaUltimaSincronizacionArticulosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaUltimaSincronizacionArticulosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaUltimaSincronizacionArticulosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void FechaUltimaSincronizacionCuentasCompletedEventHandler(object sender, FechaUltimaSincronizacionCuentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaUltimaSincronizacionCuentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaUltimaSincronizacionCuentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void FechaUltimaSincronizacionClientesCompletedEventHandler(object sender, FechaUltimaSincronizacionClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaUltimaSincronizacionClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaUltimaSincronizacionClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void FechaUltimaSincronizacionZonasCompletedEventHandler(object sender, FechaUltimaSincronizacionZonasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaUltimaSincronizacionZonasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaUltimaSincronizacionZonasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void EnviarArticuloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void EnviarCuentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void EnviarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void IniciarEnvioVentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void EnviarVentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void TerminarEnvioVentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void EnviarZonaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void EliminarFamiliasArticuloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void EnviarFamiliaArticuloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void EliminarFamiliasArticuloXArticuloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void EnviarFamiliaArticuloXArticuloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void RecibirRollingForecastCompletedEventHandler(object sender, RecibirRollingForecastCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecibirRollingForecastCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecibirRollingForecastCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Forecast[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Forecast[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void RecibirProyeccionAnualCompletedEventHandler(object sender, RecibirProyeccionAnualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecibirProyeccionAnualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecibirProyeccionAnualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Forecast[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Forecast[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591