//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.4927.
// 
#pragma warning disable 1591

namespace CedForecastRN.WS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SincronizacionSoap", Namespace="http://cedeira.com.ar/")]
    public partial class Sincronizacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FechaUltimaSincronizacionArticulosOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaUltimaSincronizacionCuentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaUltimaSincronizacionClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaUltimaSincronizacionZonasOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarArticuloOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarZonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecibirForecastOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Sincronizacion() {
            this.Url = global::CedForecastRN.Properties.Settings.Default.CedForecastRN_WS_Sincronizacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FechaUltimaSincronizacionArticulosCompletedEventHandler FechaUltimaSincronizacionArticulosCompleted;
        
        /// <remarks/>
        public event FechaUltimaSincronizacionCuentasCompletedEventHandler FechaUltimaSincronizacionCuentasCompleted;
        
        /// <remarks/>
        public event FechaUltimaSincronizacionClientesCompletedEventHandler FechaUltimaSincronizacionClientesCompleted;
        
        /// <remarks/>
        public event FechaUltimaSincronizacionZonasCompletedEventHandler FechaUltimaSincronizacionZonasCompleted;
        
        /// <remarks/>
        public event EnviarArticuloCompletedEventHandler EnviarArticuloCompleted;
        
        /// <remarks/>
        public event EnviarCuentaCompletedEventHandler EnviarCuentaCompleted;
        
        /// <remarks/>
        public event EnviarClienteCompletedEventHandler EnviarClienteCompleted;
        
        /// <remarks/>
        public event EnviarVentasCompletedEventHandler EnviarVentasCompleted;
        
        /// <remarks/>
        public event EnviarZonaCompletedEventHandler EnviarZonaCompleted;
        
        /// <remarks/>
        public event RecibirForecastCompletedEventHandler RecibirForecastCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/FechaUltimaSincronizacionArticulos", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime FechaUltimaSincronizacionArticulos() {
            object[] results = this.Invoke("FechaUltimaSincronizacionArticulos", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionArticulosAsync() {
            this.FechaUltimaSincronizacionArticulosAsync(null);
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionArticulosAsync(object userState) {
            if ((this.FechaUltimaSincronizacionArticulosOperationCompleted == null)) {
                this.FechaUltimaSincronizacionArticulosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaUltimaSincronizacionArticulosOperationCompleted);
            }
            this.InvokeAsync("FechaUltimaSincronizacionArticulos", new object[0], this.FechaUltimaSincronizacionArticulosOperationCompleted, userState);
        }
        
        private void OnFechaUltimaSincronizacionArticulosOperationCompleted(object arg) {
            if ((this.FechaUltimaSincronizacionArticulosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaUltimaSincronizacionArticulosCompleted(this, new FechaUltimaSincronizacionArticulosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/FechaUltimaSincronizacionCuentas", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime FechaUltimaSincronizacionCuentas() {
            object[] results = this.Invoke("FechaUltimaSincronizacionCuentas", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionCuentasAsync() {
            this.FechaUltimaSincronizacionCuentasAsync(null);
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionCuentasAsync(object userState) {
            if ((this.FechaUltimaSincronizacionCuentasOperationCompleted == null)) {
                this.FechaUltimaSincronizacionCuentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaUltimaSincronizacionCuentasOperationCompleted);
            }
            this.InvokeAsync("FechaUltimaSincronizacionCuentas", new object[0], this.FechaUltimaSincronizacionCuentasOperationCompleted, userState);
        }
        
        private void OnFechaUltimaSincronizacionCuentasOperationCompleted(object arg) {
            if ((this.FechaUltimaSincronizacionCuentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaUltimaSincronizacionCuentasCompleted(this, new FechaUltimaSincronizacionCuentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/FechaUltimaSincronizacionClientes", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime FechaUltimaSincronizacionClientes() {
            object[] results = this.Invoke("FechaUltimaSincronizacionClientes", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionClientesAsync() {
            this.FechaUltimaSincronizacionClientesAsync(null);
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionClientesAsync(object userState) {
            if ((this.FechaUltimaSincronizacionClientesOperationCompleted == null)) {
                this.FechaUltimaSincronizacionClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaUltimaSincronizacionClientesOperationCompleted);
            }
            this.InvokeAsync("FechaUltimaSincronizacionClientes", new object[0], this.FechaUltimaSincronizacionClientesOperationCompleted, userState);
        }
        
        private void OnFechaUltimaSincronizacionClientesOperationCompleted(object arg) {
            if ((this.FechaUltimaSincronizacionClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaUltimaSincronizacionClientesCompleted(this, new FechaUltimaSincronizacionClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/FechaUltimaSincronizacionZonas", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime FechaUltimaSincronizacionZonas() {
            object[] results = this.Invoke("FechaUltimaSincronizacionZonas", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionZonasAsync() {
            this.FechaUltimaSincronizacionZonasAsync(null);
        }
        
        /// <remarks/>
        public void FechaUltimaSincronizacionZonasAsync(object userState) {
            if ((this.FechaUltimaSincronizacionZonasOperationCompleted == null)) {
                this.FechaUltimaSincronizacionZonasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaUltimaSincronizacionZonasOperationCompleted);
            }
            this.InvokeAsync("FechaUltimaSincronizacionZonas", new object[0], this.FechaUltimaSincronizacionZonasOperationCompleted, userState);
        }
        
        private void OnFechaUltimaSincronizacionZonasOperationCompleted(object arg) {
            if ((this.FechaUltimaSincronizacionZonasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaUltimaSincronizacionZonasCompleted(this, new FechaUltimaSincronizacionZonasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarArticulo", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarArticulo(Articulo Elemento) {
            this.Invoke("EnviarArticulo", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarArticuloAsync(Articulo Elemento) {
            this.EnviarArticuloAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarArticuloAsync(Articulo Elemento, object userState) {
            if ((this.EnviarArticuloOperationCompleted == null)) {
                this.EnviarArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarArticuloOperationCompleted);
            }
            this.InvokeAsync("EnviarArticulo", new object[] {
                        Elemento}, this.EnviarArticuloOperationCompleted, userState);
        }
        
        private void OnEnviarArticuloOperationCompleted(object arg) {
            if ((this.EnviarArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarArticuloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarCuenta", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarCuenta(Cuenta Elemento) {
            this.Invoke("EnviarCuenta", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarCuentaAsync(Cuenta Elemento) {
            this.EnviarCuentaAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarCuentaAsync(Cuenta Elemento, object userState) {
            if ((this.EnviarCuentaOperationCompleted == null)) {
                this.EnviarCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarCuentaOperationCompleted);
            }
            this.InvokeAsync("EnviarCuenta", new object[] {
                        Elemento}, this.EnviarCuentaOperationCompleted, userState);
        }
        
        private void OnEnviarCuentaOperationCompleted(object arg) {
            if ((this.EnviarCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarCuentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarCliente", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarCliente(Cliente Elemento) {
            this.Invoke("EnviarCliente", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarClienteAsync(Cliente Elemento) {
            this.EnviarClienteAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarClienteAsync(Cliente Elemento, object userState) {
            if ((this.EnviarClienteOperationCompleted == null)) {
                this.EnviarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarClienteOperationCompleted);
            }
            this.InvokeAsync("EnviarCliente", new object[] {
                        Elemento}, this.EnviarClienteOperationCompleted, userState);
        }
        
        private void OnEnviarClienteOperationCompleted(object arg) {
            if ((this.EnviarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarVentas", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarVentas(Venta[] Lista) {
            this.Invoke("EnviarVentas", new object[] {
                        Lista});
        }
        
        /// <remarks/>
        public void EnviarVentasAsync(Venta[] Lista) {
            this.EnviarVentasAsync(Lista, null);
        }
        
        /// <remarks/>
        public void EnviarVentasAsync(Venta[] Lista, object userState) {
            if ((this.EnviarVentasOperationCompleted == null)) {
                this.EnviarVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarVentasOperationCompleted);
            }
            this.InvokeAsync("EnviarVentas", new object[] {
                        Lista}, this.EnviarVentasOperationCompleted, userState);
        }
        
        private void OnEnviarVentasOperationCompleted(object arg) {
            if ((this.EnviarVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarVentasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/EnviarZona", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarZona(Zona Elemento) {
            this.Invoke("EnviarZona", new object[] {
                        Elemento});
        }
        
        /// <remarks/>
        public void EnviarZonaAsync(Zona Elemento) {
            this.EnviarZonaAsync(Elemento, null);
        }
        
        /// <remarks/>
        public void EnviarZonaAsync(Zona Elemento, object userState) {
            if ((this.EnviarZonaOperationCompleted == null)) {
                this.EnviarZonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarZonaOperationCompleted);
            }
            this.InvokeAsync("EnviarZona", new object[] {
                        Elemento}, this.EnviarZonaOperationCompleted, userState);
        }
        
        private void OnEnviarZonaOperationCompleted(object arg) {
            if ((this.EnviarZonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarZonaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cedeira.com.ar/RecibirForecast", RequestNamespace="http://cedeira.com.ar/", ResponseNamespace="http://cedeira.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Forecast[] RecibirForecast(System.DateTime Fecha) {
            object[] results = this.Invoke("RecibirForecast", new object[] {
                        Fecha});
            return ((Forecast[])(results[0]));
        }
        
        /// <remarks/>
        public void RecibirForecastAsync(System.DateTime Fecha) {
            this.RecibirForecastAsync(Fecha, null);
        }
        
        /// <remarks/>
        public void RecibirForecastAsync(System.DateTime Fecha, object userState) {
            if ((this.RecibirForecastOperationCompleted == null)) {
                this.RecibirForecastOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecibirForecastOperationCompleted);
            }
            this.InvokeAsync("RecibirForecast", new object[] {
                        Fecha}, this.RecibirForecastOperationCompleted, userState);
        }
        
        private void OnRecibirForecastOperationCompleted(object arg) {
            if ((this.RecibirForecastCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecibirForecastCompleted(this, new RecibirForecastCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Articulo {
        
        private string idArticuloField;
        
        private string descrArticuloField;
        
        private decimal pesoBrutoField;
        
        private string unidadMedidaField;
        
        private bool habilitadoField;
        
        private System.DateTime fechaUltModifField;
        
        private GrupoArticulo grupoArticuloField;
        
        /// <comentarios/>
        public string IdArticulo {
            get {
                return this.idArticuloField;
            }
            set {
                this.idArticuloField = value;
            }
        }
        
        /// <comentarios/>
        public string DescrArticulo {
            get {
                return this.descrArticuloField;
            }
            set {
                this.descrArticuloField = value;
            }
        }
        
        /// <comentarios/>
        public decimal PesoBruto {
            get {
                return this.pesoBrutoField;
            }
            set {
                this.pesoBrutoField = value;
            }
        }
        
        /// <comentarios/>
        public string UnidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
            }
        }
        
        /// <comentarios/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaUltModif {
            get {
                return this.fechaUltModifField;
            }
            set {
                this.fechaUltModifField = value;
            }
        }
        
        /// <comentarios/>
        public GrupoArticulo GrupoArticulo {
            get {
                return this.grupoArticuloField;
            }
            set {
                this.grupoArticuloField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class GrupoArticulo {
        
        private string idGrupoArticuloField;
        
        private string descrGrupoArticuloField;
        
        private Division divisionField;
        
        /// <comentarios/>
        public string IdGrupoArticulo {
            get {
                return this.idGrupoArticuloField;
            }
            set {
                this.idGrupoArticuloField = value;
            }
        }
        
        /// <comentarios/>
        public string DescrGrupoArticulo {
            get {
                return this.descrGrupoArticuloField;
            }
            set {
                this.descrGrupoArticuloField = value;
            }
        }
        
        /// <comentarios/>
        public Division Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Division {
        
        private string idDivisionField;
        
        private string descrDivisionField;
        
        /// <comentarios/>
        public string IdDivision {
            get {
                return this.idDivisionField;
            }
            set {
                this.idDivisionField = value;
            }
        }
        
        /// <comentarios/>
        public string DescrDivision {
            get {
                return this.descrDivisionField;
            }
            set {
                this.descrDivisionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Forecast {
        
        private string idCuentaField;
        
        private string idClienteField;
        
        private Articulo articuloField;
        
        private System.DateTime fechaField;
        
        private decimal cantidad1Field;
        
        private decimal cantidad2Field;
        
        private decimal cantidad3Field;
        
        private decimal cantidad4Field;
        
        private decimal cantidad5Field;
        
        private decimal cantidad6Field;
        
        private decimal cantidad7Field;
        
        private decimal cantidad8Field;
        
        private decimal cantidad9Field;
        
        private decimal cantidad10Field;
        
        private decimal cantidad11Field;
        
        private decimal cantidad12Field;
        
        /// <comentarios/>
        public string IdCuenta {
            get {
                return this.idCuentaField;
            }
            set {
                this.idCuentaField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <comentarios/>
        public Articulo Articulo {
            get {
                return this.articuloField;
            }
            set {
                this.articuloField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad1 {
            get {
                return this.cantidad1Field;
            }
            set {
                this.cantidad1Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad2 {
            get {
                return this.cantidad2Field;
            }
            set {
                this.cantidad2Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad3 {
            get {
                return this.cantidad3Field;
            }
            set {
                this.cantidad3Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad4 {
            get {
                return this.cantidad4Field;
            }
            set {
                this.cantidad4Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad5 {
            get {
                return this.cantidad5Field;
            }
            set {
                this.cantidad5Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad6 {
            get {
                return this.cantidad6Field;
            }
            set {
                this.cantidad6Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad7 {
            get {
                return this.cantidad7Field;
            }
            set {
                this.cantidad7Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad8 {
            get {
                return this.cantidad8Field;
            }
            set {
                this.cantidad8Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad9 {
            get {
                return this.cantidad9Field;
            }
            set {
                this.cantidad9Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad10 {
            get {
                return this.cantidad10Field;
            }
            set {
                this.cantidad10Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad11 {
            get {
                return this.cantidad11Field;
            }
            set {
                this.cantidad11Field = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad12 {
            get {
                return this.cantidad12Field;
            }
            set {
                this.cantidad12Field = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Venta {
        
        private string idArticuloField;
        
        private string idClienteField;
        
        private System.DateTime fechaForecastField;
        
        private decimal cantidadMesAnteriorField;
        
        private decimal cantidadUltimoAñoField;
        
        /// <comentarios/>
        public string IdArticulo {
            get {
                return this.idArticuloField;
            }
            set {
                this.idArticuloField = value;
            }
        }
        
        /// <comentarios/>
        public string IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaForecast {
            get {
                return this.fechaForecastField;
            }
            set {
                this.fechaForecastField = value;
            }
        }
        
        /// <comentarios/>
        public decimal CantidadMesAnterior {
            get {
                return this.cantidadMesAnteriorField;
            }
            set {
                this.cantidadMesAnteriorField = value;
            }
        }
        
        /// <comentarios/>
        public decimal CantidadUltimoAño {
            get {
                return this.cantidadUltimoAñoField;
            }
            set {
                this.cantidadUltimoAñoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Zona {
        
        private string idZonaField;
        
        private string descrZonaField;
        
        private bool habilitadaField;
        
        private System.DateTime fechaUltModifField;
        
        /// <comentarios/>
        public string IdZona {
            get {
                return this.idZonaField;
            }
            set {
                this.idZonaField = value;
            }
        }
        
        /// <comentarios/>
        public string DescrZona {
            get {
                return this.descrZonaField;
            }
            set {
                this.descrZonaField = value;
            }
        }
        
        /// <comentarios/>
        public bool Habilitada {
            get {
                return this.habilitadaField;
            }
            set {
                this.habilitadaField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaUltModif {
            get {
                return this.fechaUltModifField;
            }
            set {
                this.fechaUltModifField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Cliente {
        
        private string idClienteField;
        
        private string descrClienteField;
        
        private Zona zonaField;
        
        private bool habilitadoField;
        
        private System.DateTime fechaUltModifField;
        
        /// <comentarios/>
        public string IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <comentarios/>
        public string DescrCliente {
            get {
                return this.descrClienteField;
            }
            set {
                this.descrClienteField = value;
            }
        }
        
        /// <comentarios/>
        public Zona Zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
            }
        }
        
        /// <comentarios/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaUltModif {
            get {
                return this.fechaUltModifField;
            }
            set {
                this.fechaUltModifField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class PaginaDefault {
        
        private string idField;
        
        private string descrField;
        
        private string uRLField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
        
        /// <comentarios/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class EstadoCuenta {
        
        private string idField;
        
        private string descrField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class TipoCuenta {
        
        private string idField;
        
        private string descrField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cedeira.com.ar/")]
    public partial class Cuenta {
        
        private string idField;
        
        private string nombreField;
        
        private string telefonoField;
        
        private string emailField;
        
        private Division divisionField;
        
        private string passwordField;
        
        private string confirmacionPasswordField;
        
        private string preguntaField;
        
        private string respuestaField;
        
        private TipoCuenta tipoCuentaField;
        
        private EstadoCuenta estadoCuentaField;
        
        private System.DateTime fechaAltaField;
        
        private int cantidadEnviosMailField;
        
        private System.DateTime fechaUltimoReenvioMailField;
        
        private string emailSMSField;
        
        private bool recibeAvisoAltaCuentaField;
        
        private PaginaDefault paginaDefaultField;
        
        /// <comentarios/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <comentarios/>
        public Division Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <comentarios/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <comentarios/>
        public string ConfirmacionPassword {
            get {
                return this.confirmacionPasswordField;
            }
            set {
                this.confirmacionPasswordField = value;
            }
        }
        
        /// <comentarios/>
        public string Pregunta {
            get {
                return this.preguntaField;
            }
            set {
                this.preguntaField = value;
            }
        }
        
        /// <comentarios/>
        public string Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <comentarios/>
        public TipoCuenta TipoCuenta {
            get {
                return this.tipoCuentaField;
            }
            set {
                this.tipoCuentaField = value;
            }
        }
        
        /// <comentarios/>
        public EstadoCuenta EstadoCuenta {
            get {
                return this.estadoCuentaField;
            }
            set {
                this.estadoCuentaField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaAlta {
            get {
                return this.fechaAltaField;
            }
            set {
                this.fechaAltaField = value;
            }
        }
        
        /// <comentarios/>
        public int CantidadEnviosMail {
            get {
                return this.cantidadEnviosMailField;
            }
            set {
                this.cantidadEnviosMailField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaUltimoReenvioMail {
            get {
                return this.fechaUltimoReenvioMailField;
            }
            set {
                this.fechaUltimoReenvioMailField = value;
            }
        }
        
        /// <comentarios/>
        public string EmailSMS {
            get {
                return this.emailSMSField;
            }
            set {
                this.emailSMSField = value;
            }
        }
        
        /// <comentarios/>
        public bool RecibeAvisoAltaCuenta {
            get {
                return this.recibeAvisoAltaCuentaField;
            }
            set {
                this.recibeAvisoAltaCuentaField = value;
            }
        }
        
        /// <comentarios/>
        public PaginaDefault PaginaDefault {
            get {
                return this.paginaDefaultField;
            }
            set {
                this.paginaDefaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void FechaUltimaSincronizacionArticulosCompletedEventHandler(object sender, FechaUltimaSincronizacionArticulosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaUltimaSincronizacionArticulosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaUltimaSincronizacionArticulosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void FechaUltimaSincronizacionCuentasCompletedEventHandler(object sender, FechaUltimaSincronizacionCuentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaUltimaSincronizacionCuentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaUltimaSincronizacionCuentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void FechaUltimaSincronizacionClientesCompletedEventHandler(object sender, FechaUltimaSincronizacionClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaUltimaSincronizacionClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaUltimaSincronizacionClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void FechaUltimaSincronizacionZonasCompletedEventHandler(object sender, FechaUltimaSincronizacionZonasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaUltimaSincronizacionZonasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaUltimaSincronizacionZonasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void EnviarArticuloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void EnviarCuentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void EnviarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void EnviarVentasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void EnviarZonaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RecibirForecastCompletedEventHandler(object sender, RecibirForecastCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecibirForecastCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecibirForecastCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Forecast[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Forecast[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591